---
- name: set hostname
  hostname: "{{ my_host_var }}"

- name: add group "docker"
  group: 
    name: docker

- name: add user "docker"
  user: 
    name: docker
    group: docker
    home: "/home/docker"

- name: Join K8S cluster
  shell: /bin/bash -lc "{{ token_info }}}"


