---
- name: add group "docker"
  group: 
    name: docker

- name: add user "docker"
  user: 
    name: docker
    group: docker
    home: "/home/docker"

- name: Check if aready joined to Cluster
  stat:
    path: /var/lib/kubelet/config.yaml
  register: _joined

- name: Join K8S cluster
#  shell: /bin/bash -lc "{{ token_info }}}"
  shell: "{{ token_info }}"
  when: not _joined.stat.exists

